[package]
name = "hire-me"
version = "0.1.0"
authors = ["giacomo <giacomo.dantonio@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0"
lazy_static = "1"
